version: "3.0"
services:

  postgres:
    image: postgres:9.4
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    ports:
    - "9000:8080"
